def show_main():
    print('1) 添加')
    print('2) 显示 ')
    print('3) 删除 ')
    print('4) 修改 ')
    print('5)按学生成绩高~低显示学生信息')
    print('6)按学生成绩低~高显示学生信息')
    print('7)按学生年龄高~低显示学生信息')
    print('8)按学生年龄低~高显示学生信息')
    print('9)从文件中读取数据(si.txt)')
    print('10)保存信息到文件(si.txt)')
    print('q) 退出')